apiVersion: v1
kind: Namespace
metadata:
  name: healthmed

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: healthmed
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: healthmed
spec:
  type: NodePort
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31433

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "YourStrong!Passw0rd"
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: mssql-data
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: sqlserver-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: healthmed
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30880

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: healthmed-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver;Database=HealthMed;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True"

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: healthmed
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30881

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: healthmed-web
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"