--https://sistemas.cfm.org.br/normas/visualizar/resolucoes/BR/2023/2330
SET IDENTITY_INSERT dbo.Especialidade ON

INSERT INTO dbo.Especialidade (Id, Nome) VALUES (1, 'Acupuntura')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (2, 'Alergia e imunologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (3, 'Anestesiologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (4, 'Angiologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (5, 'Cardiologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (6, 'Cirurgia cardiovascular')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (7, 'Cirurgia da mão')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (8, 'Cirurgia de cabeça e pescoço')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (9, 'Cirurgia do aparelho digestivo')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (10, 'Cirurgia geral')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (11, 'Cirurgia oncológica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (12, 'Cirurgia pediátrica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (13, 'Cirurgia plástica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (14, 'Cirurgia torácica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (15, 'Cirurgia vascular')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (16, 'Clínica médica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (17, 'Coloproctologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (18, 'Dermatologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (19, 'Endocrinologia e metabologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (20, 'Endoscopia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (21, 'Gastroenterologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (22, 'Genética médica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (23, 'Geriatria')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (24, 'Ginecologia e obstetrícia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (25, 'Hematologia e hemoterapia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (26, 'Homeopatia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (27, 'Infectologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (28, 'Mastologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (29, 'Medicina de emergência')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (30, 'Medicina de família e comunidade')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (31, 'Medicina do trabalho')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (32, 'Medicina do tráfego')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (33, 'Medicina esportiva')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (34, 'Medicina física e reabilitação')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (35, 'Medicina intensiva')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (36, 'Medicina legal e perícia médica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (37, 'Medicina nuclear')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (38, 'Medicina preventiva e social')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (39, 'Nefrologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (40, 'Neurocirurgia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (41, 'Neurologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (42, 'Nutrologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (43, 'Oftalmologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (44, 'Oncologia clínica')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (45, 'Ortopedia e traumatologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (46, 'Otorrinolaringologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (47, 'Patologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (48, 'Patologia clínica/medicina laboratorial')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (49, 'Pediatria')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (50, 'Pneumologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (51, 'Psiquiatria')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (52, 'Radiologia e diagnóstico por imagem')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (53, 'Radioterapia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (54, 'Reumatologia')
INSERT INTO dbo.Especialidade (Id, Nome) VALUES (55, 'Urologia')

SET IDENTITY_INSERT dbo.Especialidade OFF
